package com.indus.dao.hibernate;

// Generated 21-Jun-2011 15:13:39 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catalog generated by hbm2java
 */
public class Catalog implements java.io.Serializable {

	private Integer itemId;
	private Cat cat;
	private String name;
	private Float price;
	private Integer targetId;
	private Integer stock;
	private String color;
	private String size;
	private Float weight;
	private String material;
	private String description;
	private String image;
	private String icon;
	private Integer hotindex;
	private Integer discount;
	private Date updatedon;
	private Set orderitemses = new HashSet(0);

	public Catalog() {
	}

	public Catalog(String name, String image) {
		this.name = name;
		this.image = image;
	}

	public Catalog(Cat cat, String name, Float price, Integer targetId,
			Integer stock, String color, String size, Float weight,
			String material, String description, String image, String icon,
			Integer hotindex, Integer discount, Date updatedon, Set orderitemses) {
		this.cat = cat;
		this.name = name;
		this.price = price;
		this.targetId = targetId;
		this.stock = stock;
		this.color = color;
		this.size = size;
		this.weight = weight;
		this.material = material;
		this.description = description;
		this.image = image;
		this.icon = icon;
		this.hotindex = hotindex;
		this.discount = discount;
		this.updatedon = updatedon;
		this.orderitemses = orderitemses;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public Cat getCat() {
		return this.cat;
	}

	public void setCat(Cat cat) {
		this.cat = cat;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Integer getTargetId() {
		return this.targetId;
	}

	public void setTargetId(Integer targetId) {
		this.targetId = targetId;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Integer getHotindex() {
		return this.hotindex;
	}

	public void setHotindex(Integer hotindex) {
		this.hotindex = hotindex;
	}

	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	public Set getOrderitemses() {
		return this.orderitemses;
	}

	public void setOrderitemses(Set orderitemses) {
		this.orderitemses = orderitemses;
	}

}
