package com.indus.dao.hibernate;

// Generated 21-Jun-2011 15:13:39 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private String email;
	private Address addressByShipaddressid;
	private Address addressByAddressid;
	private String name;
	private String username;
	private String password;
	private Long phone;
	private Long mobile;
	private Set orderses = new HashSet(0);

	public Customer() {
	}

	public Customer(String email) {
		this.email = email;
	}

	public Customer(String email, Address addressByShipaddressid,
			Address addressByAddressid, String name, String username,
			String password, Long phone, Long mobile, Set orderses) {
		this.email = email;
		this.addressByShipaddressid = addressByShipaddressid;
		this.addressByAddressid = addressByAddressid;
		this.name = name;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.mobile = mobile;
		this.orderses = orderses;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Address getAddressByShipaddressid() {
		return this.addressByShipaddressid;
	}

	public void setAddressByShipaddressid(Address addressByShipaddressid) {
		this.addressByShipaddressid = addressByShipaddressid;
	}

	public Address getAddressByAddressid() {
		return this.addressByAddressid;
	}

	public void setAddressByAddressid(Address addressByAddressid) {
		this.addressByAddressid = addressByAddressid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Long getPhone() {
		return this.phone;
	}

	public void setPhone(Long phone) {
		this.phone = phone;
	}

	public Long getMobile() {
		return this.mobile;
	}

	public void setMobile(Long mobile) {
		this.mobile = mobile;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
