package com.indus.dao.hibernate;

// Generated 21-Jun-2011 15:13:39 by Hibernate Tools 3.4.0.Beta1

/**
 * Orderitems generated by hbm2java
 */
public class Orderitems implements java.io.Serializable {

	private OrderitemsId id;
	private Orders orders;
	private Catalog catalog;

	public Orderitems() {
	}

	public Orderitems(OrderitemsId id) {
		this.id = id;
	}

	public Orderitems(OrderitemsId id, Orders orders, Catalog catalog) {
		this.id = id;
		this.orders = orders;
		this.catalog = catalog;
	}

	public OrderitemsId getId() {
		return this.id;
	}

	public void setId(OrderitemsId id) {
		this.id = id;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Catalog getCatalog() {
		return this.catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

}
