package com.indus.dao.hibernate;

// Generated 21-Jun-2011 15:13:39 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer orderid;
	private Customer customer;
	private Shipping shipping;
	private Payment payment;
	private Float amount;
	private Date orderdate;
	private Integer status;
	private Date shippingdate;
	private String comments;
	private Set orderitemses = new HashSet(0);

	public Orders() {
	}

	public Orders(Customer customer, Shipping shipping, Payment payment,
			Float amount, Date orderdate, Integer status, Date shippingdate,
			String comments, Set orderitemses) {
		this.customer = customer;
		this.shipping = shipping;
		this.payment = payment;
		this.amount = amount;
		this.orderdate = orderdate;
		this.status = status;
		this.shippingdate = shippingdate;
		this.comments = comments;
		this.orderitemses = orderitemses;
	}

	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Shipping getShipping() {
		return this.shipping;
	}

	public void setShipping(Shipping shipping) {
		this.shipping = shipping;
	}

	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getShippingdate() {
		return this.shippingdate;
	}

	public void setShippingdate(Date shippingdate) {
		this.shippingdate = shippingdate;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set getOrderitemses() {
		return this.orderitemses;
	}

	public void setOrderitemses(Set orderitemses) {
		this.orderitemses = orderitemses;
	}

}
