package com.indus.dao.hibernate;

// Generated 21-Jun-2011 15:13:39 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer paymentid;
	private Integer type;
	private Float amount;
	private Integer status;
	private String paymentdetails;
	private Date paymentdate;
	private String comments;
	private Set orderses = new HashSet(0);

	public Payment() {
	}

	public Payment(Integer type, Float amount, Integer status,
			String paymentdetails, Date paymentdate, String comments,
			Set orderses) {
		this.type = type;
		this.amount = amount;
		this.status = status;
		this.paymentdetails = paymentdetails;
		this.paymentdate = paymentdate;
		this.comments = comments;
		this.orderses = orderses;
	}

	public Integer getPaymentid() {
		return this.paymentid;
	}

	public void setPaymentid(Integer paymentid) {
		this.paymentid = paymentid;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getPaymentdetails() {
		return this.paymentdetails;
	}

	public void setPaymentdetails(String paymentdetails) {
		this.paymentdetails = paymentdetails;
	}

	public Date getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(Date paymentdate) {
		this.paymentdate = paymentdate;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
