package com.indus.dao.hibernate;

// Generated 09-Jul-2011 00:48:35 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer paymentid;
	private String transactionid;
	private Integer type;
	private Float amount;
	private Integer status;
	private Date paymentdate;
	private String comments;
	private Set orderses = new HashSet(0);

	public Payment() {
	}

	public Payment(String transactionid, Integer type, Float amount,
			Integer status, Date paymentdate, String comments, Set orderses) {
		this.transactionid = transactionid;
		this.type = type;
		this.amount = amount;
		this.status = status;
		this.paymentdate = paymentdate;
		this.comments = comments;
		this.orderses = orderses;
	}

	public Integer getPaymentid() {
		return this.paymentid;
	}

	public void setPaymentid(Integer paymentid) {
		this.paymentid = paymentid;
	}

	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(Date paymentdate) {
		this.paymentdate = paymentdate;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
