package com.indus.dao.hibernate;

// Generated 09-Jul-2011 00:48:35 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Shipping generated by hbm2java
 */
public class Shipping implements java.io.Serializable {

	private Integer shippingid;
	private Country country;
	private String name;
	private String description;
	private Integer days;
	private Float cost;
	private Float duty;
	private Float taxes;
	private String restrictions;
	private String sizelimit;
	private Float weightlimit;
	private Set orderses = new HashSet(0);

	public Shipping() {
	}

	public Shipping(Country country, String name, String description,
			Integer days, Float cost, Float duty, Float taxes,
			String restrictions, String sizelimit, Float weightlimit,
			Set orderses) {
		this.country = country;
		this.name = name;
		this.description = description;
		this.days = days;
		this.cost = cost;
		this.duty = duty;
		this.taxes = taxes;
		this.restrictions = restrictions;
		this.sizelimit = sizelimit;
		this.weightlimit = weightlimit;
		this.orderses = orderses;
	}

	public Integer getShippingid() {
		return this.shippingid;
	}

	public void setShippingid(Integer shippingid) {
		this.shippingid = shippingid;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	public Float getCost() {
		return this.cost;
	}

	public void setCost(Float cost) {
		this.cost = cost;
	}

	public Float getDuty() {
		return this.duty;
	}

	public void setDuty(Float duty) {
		this.duty = duty;
	}

	public Float getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Float taxes) {
		this.taxes = taxes;
	}

	public String getRestrictions() {
		return this.restrictions;
	}

	public void setRestrictions(String restrictions) {
		this.restrictions = restrictions;
	}

	public String getSizelimit() {
		return this.sizelimit;
	}

	public void setSizelimit(String sizelimit) {
		this.sizelimit = sizelimit;
	}

	public Float getWeightlimit() {
		return this.weightlimit;
	}

	public void setWeightlimit(Float weightlimit) {
		this.weightlimit = weightlimit;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
